### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by Ramgaming** [evancolewright/HeadDrops#13]
### Plugin Version
1.5.6

### Server Version
paper 1.18.2

### StackTrace
**[02:44:03] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to HeadDrops v1.5.6
java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
	at java.util.UUID.fromString(UUID.java:258) ~[?:?]
	at com.github.evancolewright.headdrops.model.PlayerHeadData.fromPlacedHead(PlayerHeadData.java:34) ~[HeadDrops-1.5.6.jar:?]
	at com.github.evancolewright.headdrops.HeadDropsListeners.onHeadPlace(HeadDropsListeners.java:64) ~[HeadDrops-1.5.6.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor42.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-386]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:393) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:383) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:625) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1852) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]**

### Steps to Reproduce
I dnt know exactly when it spaming, I just find this in my console all time when I was looking my console for some reason.

**Comment by evancolewright** [comment]
Thanks for reporting an issue.  I'm not entirely sure the cause, but I'll look into it later tonight.

**Comment by evancolewright** [comment]
I am unable to replicate this bug.  I have tested based on the stack trace you sent, and it all seems to work for me on 1.18.2. 

Just as a question, were you using HeadDrops prior to the 1.5.6 update?

**Comment by Ramgaming** [comment]
> Just as a question, were you using HeadDrops prior to the 1.5.6 update?

nope

**Comment by OmarYC** [comment]
I am having the same problem

**Comment by evancolewright** [comment]
> I am having the same problem

Do you have a way of reproducing this error?  I had previously tried myself, but I personally  could never find any errors in console.
