### ISSUE TITLE
Could not pass event BlockPlaceEvent to HeadDrops v1.5.6

### ISSUE THREAD

**Issue by TheDamStex** [evancolewright/HeadDrops#30]
[18:48:46 ERROR]: Could not pass event BlockPlaceEvent to HeadDrops v1.5.6
java.lang.IllegalArgumentException: Invalid UUID string: 
        at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
        at java.util.UUID.fromString(UUID.java:258) ~[?:?]
        at com.github.evancolewright.headdrops.model.PlayerHeadData.fromPlacedHead(PlayerHeadData.java:34) ~[HeadDrops-1.5.6.jar:?]
        at com.github.evancolewright.headdrops.HeadDropsListeners.onHeadPlace(HeadDropsListeners.java:64) ~[HeadDrops-1.5.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:git-Pufferfish-58]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:674) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:397) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:404) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:590) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by K4sum1** [comment]
I get this error too. Doesn't seem to effect functionality, but I don't like the console spam.
