### ISSUE TITLE
Player heads not dropping after being broken

### ISSUE THREAD

**Issue by TreeOfSelf** [evancolewright/HeadDrops#7]
### Plugin Version

1.5.2

### Server Version

git-Pufferfish-67

### StackTrace

`[01:09:36 ERROR]: Could not pass event BlockBreakEvent to HeadDrops v1.5.2
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because the return value of "org.bukkit.Bukkit.getPlayer(java.util.UUID)" is null
        at com.github.evancolewright.headdrops.utilities.HeadUtils.createPlayerHead(HeadUtils.java:30) ~[HeadDrops-v1.5.2.jar:?]
        at com.github.evancolewright.headdrops.model.PlayerHeadData.toItemStack(PlayerHeadData.java:44) ~[HeadDrops-v1.5.2.jar:?]
        at com.github.evancolewright.headdrops.HeadDropsListeners.onHeadBreak(HeadDropsListeners.java:76) ~[HeadDrops-v1.5.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:git-Pufferfish-68]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:412) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:366) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:324) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1770) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:14) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`
### Steps to Reproduce

Place player head, break player head. I tried regenerating my configs, same thing. Also after updating this plugin and a few others, I had this very strange thing with a player joining and not being able to take damage.

**Comment by evancolewright** [comment]
Was the player that the head belonged to **offline** when this error happened?

**Comment by TreeOfSelf** [comment]
Yes, they were offline. It is a deathban server so after they die they go offline. Ok good to know the damage is something else, thank you.

**Comment by evancolewright** [comment]
Okay, I have fixed it.  The new download is available [here](https://www.spigotmc.org/resources/headdrops-1-8-1-18.15964/).  Test it out and let me know because I can't get into my alt for some reason.  

I apologize for all the issues.  Thanks for reporting them though!

**Comment by TreeOfSelf** [comment]
Hi! Firstly, I did indeed confirm the invincible thing was an entirely different plugin (I should have reasoned initially, my mistake)

Secondly, I did try the new patch and received a similar error when replacing the head
`[02:16:16 ERROR]: Could not pass event BlockBreakEvent to HeadDrops v1.5.3
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because the return value of "org.bukkit.Bukkit.getPlayer(java.util.UUID)" is null
        at com.github.evancolewright.headdrops.utilities.HeadUtils.replacePlaceHolders(HeadUtils.java:43) ~[HeadDrops-v1.5.3.jar:?]
        at com.github.evancolewright.headdrops.utilities.HeadUtils.createPlayerHead(HeadUtils.java:31) ~[HeadDrops-v1.5.3.jar:?]
        at com.github.evancolewright.headdrops.model.PlayerHeadData.toItemStack(PlayerHeadData.java:44) ~[HeadDrops-v1.5.3.jar:?]
        at com.github.evancolewright.headdrops.HeadDropsListeners.onHeadBreak(HeadDropsListeners.java:76) ~[HeadDrops-v1.5.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:git-Pufferfish-68]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:412) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:366) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:324) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1770) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:14) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>`

Thank you for your quick responses, and certainly no need to apologize. I can understand the difficulties with catching all potential problems.

**Comment by evancolewright** [comment]
> Hi! Firstly, I did indeed confirm the invincible thing was an entirely different plugin (I should have reasoned initially, my mistake)
> 
> Secondly, I did try the new patch and received a similar error when replacing the head
> 
> `[02:16:16 ERROR]: Could not pass event BlockBreakEvent to HeadDrops v1.5.3 java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because the return value of "org.bukkit.Bukkit.getPlayer(java.util.UUID)" is null at com.github.evancolewright.headdrops.utilities.HeadUtils.replacePlaceHolders(HeadUtils.java:43) ~[HeadDrops-v1.5.3.jar:?] at com.github.evancolewright.headdrops.utilities.HeadUtils.createPlayerHead(HeadUtils.java:31) ~[HeadDrops-v1.5.3.jar:?] at com.github.evancolewright.headdrops.model.PlayerHeadData.toItemStack(PlayerHeadData.java:44) ~[HeadDrops-v1.5.3.jar:?] at com.github.evancolewright.headdrops.HeadDropsListeners.onHeadBreak(HeadDropsListeners.java:76) ~[HeadDrops-v1.5.3.jar:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:git-Pufferfish-68] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?] at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:412) ~[?:?] at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:366) ~[?:?] at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:324) ~[?:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1770) ~[?:?] at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?] at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:14) ~[?:?] at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.18.2.jar:git-Pufferfish-68] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[pufferfish-1.18.2.jar:git-Pufferfish-68] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[pufferfish-1.18.2.jar:git-Pufferfish-68] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[pufferfish-1.18.2.jar:git-Pufferfish-68] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[pufferfish-1.18.2.jar:git-Pufferfish-68] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[pufferfish-1.18.2.jar:git-Pufferfish-68] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[pufferfish-1.18.2.jar:git-Pufferfish-68] at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pufferfish-1.18.2.jar:git-Pufferfish-68] at java.lang.Thread.run(Thread.java:833) ~[?:?]`
> 
> Thank you for your quick responses, and certainly no need to apologize. I can understand the difficulties with catching all potential problems. And just to be clear, the player whos head was being placed was offline at the time of placing.

Try out the release here: https://github.com/evancolewright/HeadDrops/releases/tag/Patch

**Comment by TreeOfSelf** [comment]
Ok for this version, it was almost perfect, just one last small fix

This is the head before breaking
![image](https://user-images.githubusercontent.com/53889485/169675815-defcf961-4f71-4350-a29b-8499675db698.png)
Then after breaking it turns into default steve head
![image](https://user-images.githubusercontent.com/53889485/169675829-0100a916-f166-426d-891e-374d6a2be982.png)


But when you place it down, it gets  the correct skin again. So it seems just the item version needs the correct skin.

**Comment by evancolewright** [comment]
> Ok for this version, it was almost perfect, just one last small fix
> 
> This is the head before breaking ![image](https://user-images.githubusercontent.com/53889485/169675843-e3b2c6b8-ee9f-4b26-bfd1-066feb8de824.png)
> 
> Then after breaking it turns into default steve head ![image](https://user-images.githubusercontent.com/53889485/169675829-0100a916-f166-426d-891e-374d6a2be982.png)
> 
> But when you place it down, it gets the correct skin again. So it seems just the item version needs the correct skin.

Yes, this is something I experienced occasionally in my testing.  Re-logging would usually fix this (at least for me) which led me to believe it was a Mojang thing (or maybe even a me thing).  I still don't think this is an issue with my code.  I'm going to consult with the forums to see if anyone else gets this behavior and get some ideas on how I can fix this.
